export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_PRODUCT_ITEM = 'GET_PRODUCT_ITEM';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const LOADING = 'LOADING';

export const SEARCH_PRODUCT_BY_NAME = 'SEARCH_PRODUCT_BY_NAME';

export const FILTER_BY_TYPE = 'FILTER_BY_TYPE';
export const SORT_PRODUCT = 'SORT_PRODUCT';

export const GET_CART_LOCAL = "GET_CART_LOCAL";